---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: https://backend.heurekaprints.de/webhooks/forestry/mkas13easx
sections:
- type: directory
  path: i18n
  label: Translations
  create: none
  match: "**/*"
- type: document
  path: config.yml
  label: Config.yml
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images_old
public_path: "/images_old"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.49'
